<?php

namespace Database\Seeders;

use App\Models\Apartment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $apartments = [
            [
                'user_id' => 1,
                'name' => 'Casale Castel Bolognese',
                'description' => 'Situata in cima a pittoreschi e tranquilli vigneti sulle dolci colline romagnole, La Collina è la destinazione perfetta per una vacanza in Italia. Vivi il fascino rustico della campagna con i comfort di una vita moderna grazie a un recente restauro completo. Godrete di una vista panoramica sul Mare Adriatico e sull Appennino Toscano con albe e tramonti mozzafiato e ininterrotti sulle valli circostanti.',
                'square_meters' => 220,
                'bed_number' => 8,
                'bathroom_number' => 3,
                'room_number' => 4,
                'address' => 'Via Serra, 4380, 48014 Castel bolognese',
                'city' => 'Ravenna',
                'state' => 'Italia',
                'latitude' => '44.3181599',
                'longitude' => '11.7501366',
                'price' => 600.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'La Chiocciola',
                'description' => 'Appartamento spazioso e luminoso, decorato con un elegante stile moderno. Goditi la tua colazione sulla terrazza privata con vista sulla città.',
                'square_meters' => 90,
                'bed_number' => 3,
                'bathroom_number' => 1,
                'room_number' => 2,
                'address' => 'via dei Fori Imperiali, 1, 00186',
                'city' => 'Roma',
                'state' => 'Italia',
                'latitude' => '41.893031',
                'longitude' => '12.487604',
                'price' => 150.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 2,
                'name' => 'La magica Napoli',
                'description' => 'Situata in una posizione incantevole nel quartiere Plebiscito di Napoli.',
                'square_meters' => 50,
                'bed_number' => 1,
                'bathroom_number' => 1,
                'room_number' => 1,
                'address' => 'Vico Cariati, 55',
                'city' => 'Napoli',
                'state' => 'Italia',
                'latitude' => '40.8405339',
                'longitude' => '14.244457',
                'price' => 100.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 2,
                'name' => 'Villa Elisio',
                'description' => 'Situata in una posizione incantevole nel quartiere Vomero di Napoli.',
                'square_meters' => 60,
                'bed_number' => 2,
                'bathroom_number' => 1,
                'room_number' => 6,
                'address' => 'Via Luca Samuele Cagnazzi 29',
                'city' => 'Napoli',
                'state' => 'Italia',
                'latitude' => '40.8615503',
                'longitude' => '14.2490604',
                'price' => 130.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 3,
                'name' => 'Casa Giostrello Magical Sea View in green area',
                'description' => 'Casa Giostrello è un grazioso mini-appartamento indipendente in un parco residenziale, nella zona alta di Positano e gode di una splendida vista',
                'square_meters' => 320,
                'bed_number' => 2,
                'bathroom_number' => 2,
                'room_number' => 4,
                'address' => 'Viale Pasitea',
                'city' => 'Positano',
                'state' => 'Italia',
                'latitude' => '40.62829',
                'longitude' => '14.48427',
                'price' => 190.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 3,
                'name' => 'Maison Matilde Luxury Apartment de charme',
                'description' => 'Maison Matilde  è una nuova struttura moderna situata nel cuore del centro storico, a soli 3 minuti dalla piazza principale.',
                'square_meters' => 190,
                'bed_number' => 3,
                'bathroom_number' => 2,
                'room_number' => 5,
                'address' => 'Corso Italia',
                'city' => 'Sorrento',
                'state' => 'Italia',
                'latitude' => '40.7324058',
                'longitude' => '13.9447849',
                'price' => 138.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 4,
                'name' => 'Design Club Collection',
                'description' => 'Progettato da architetti di fama internazionale, l edificio completamente ristrutturato vanta appartamenti con una selezione di iconici elementi di design moderno che uniscono qualità estetica con qualità funzionale e funzionale. Gli appartamenti sono caratterizzati dai più classici design di design, tra cui Munari, Le Corbusier, Sapper, Jacobsen, Mollino, Fratelli Castiglioni, Sottsass e Magistretti, fino ai contemporanei De Lucchi, Iosa Ghini, Starck, Grcic, Rashid, Fratelli Bourolec.',
                'square_meters' => 100,
                'bed_number' => 3,
                'bathroom_number' => 2,
                'room_number' => 3,
                'address' => 'Via Nazario Sauro, 25',
                'city' => 'Bologna',
                'state' => 'Italia',
                'latitude' => '44.49801',
                'longitude' => '11.33979',
                'price' => 200.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 4,
                'name' => 'Mini appartamento Airport_Bologna',
                'description' => 'Si tratta di un mini appartamento adatto come punto di appoggio o breve soggiorno. Vicinissimo all aeroporto MARCONI , all  OSPEDALE MAGGIORE, CENTRO COMMERCIALE "GRAN RENO", UNIPOL ARENA, CENTRO BORGO  e al MUSEO DUCATI. La zona è  ben servita da tutti i servizi, a pochi metri si trova la fermata dell autobus per raggiungere il centro.',
                'square_meters' => 30,
                'bed_number' => 1,
                'bathroom_number' => 1,
                'room_number' => 3,
                'address' => 'Via Guglielmo Pepe, 20',
                'city' => 'Bologna',
                'state' => 'Italia',
                'latitude' => '44.5231484',
                'longitude' => '11.2921357',
                'price' => 100.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'Family House',
                'description' => 'Trilocale dallo stile moderno e alla moda, con interni di design e dettagli originali. Situato in una posizione strategica, vicino alle maggiori attrazioni della città.',
                'square_meters' => 70,
                'bed_number' => 4,
                'bathroom_number' => 1,
                'room_number' => 3,
                'address' => 'via del Corso, 1',
                'city' => 'Roma',
                'state' => 'Italia',
                'latitude' => '41.90993',
                'longitude' => '12.47680',
                'price' => 225.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'Il Focolare',
                'description' => "Questo appartamento è caratterizzato dalla presenza di un bellissimo camino in pietra, che crea un'atmosfera accogliente e romantica. Gli spazi interni sono arredati con mobili in legno massello e tessuti caldi, offrendo un ambiente confortevole e rilassante. La zona living include un comodo divano-letto e una cucina completamente attrezzata, mentre la camera da letto dispone di un letto matrimoniale. L'appartamento si trova in una posizione tranquilla e panoramica, con vista sulle colline circostanti.",
                'square_meters' => 130,
                'bed_number' => 7,
                'bathroom_number' => 2,
                'room_number' => 3,
                'address' => 'via dei pozzetti, 3',
                'city' => 'Bologna',
                'state' => 'Italia',
                'latitude' => '44.46263',
                'longitude' => '11.31997',
                'price' => 145.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 3,
                'name' => 'Casa Valentino',
                'description' => "Questo appartamento è perfetto per una fuga romantica, con una vista mozzafiato sulla città e gli interni arredati con gusto e cura dei dettagli. La zona living un angolo cottura completamente attrezzato, mentre la camera da letto dispone di un letto matrimoniale e un balcone privato con vista panoramica. Il bagno è dotato di una grande vasca idromassaggio, perfetta per rilassarsi e coccolarsi in coppia.",
                'square_meters' => 110,
                'bed_number' => 5,
                'bathroom_number' => 2,
                'room_number' => 4,
                'address' => 'Via della Scala, 40, 50123 Firenze FI',
                'city' => 'Firenze',
                'state' => 'Italia',
                'latitude' => '43.775642',
                'longitude' => '11.245791',
                'price' => 245.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 2,
                'name' => 'CityLounge',
                'description' => "Questo appartamento è perfetto per chi viaggia per lavoro, con spazi interni funzionali e arredati con gusto. La zona living include una scrivania e un comodo divano-letto, mentre la camera da letto dispone di un letto matrimoniale e un grande armadio. L'appartamento è dotato di una cucina completamente attrezzata e un bagno con doccia. La posizione è centrale e ben collegata con i principali uffici e sedi di lavoro della città.",
                'square_meters' => 80,
                'bed_number' => 3,
                'bathroom_number' => 1,
                'room_number' => 3,
                'address' => 'Via Maso Finiguerra, 50123 Firenze FI',
                'city' => 'Firenze',
                'state' => 'Italia',
                'latitude' => '43.77399',
                'longitude' => '11.24508',
                'price' => 160.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 4,
                'name' => 'Caesar Executive',
                'description' => "Questo appartamento si trova nel cuore della città vecchia, in un palazzo storico completamente ristrutturato. Gli interni sono arredati in stile moderno e minimalista, creando un ambiente confortevole e accogliente. La zona living include un comodo divano-letto e un angolo cottura completamente attrezzato, mentre la camera da letto dispone di un letto matrimoniale. L'appartamento si trova in una posizione strategica, a pochi passi dalle principali attrazioni turistiche della città.",
                'square_meters' => 115,
                'bed_number' => 7,
                'bathroom_number' => 2,
                'room_number' => 3,
                'address' => 'Piazzale Angelo Moratti, 20151 Milano MI',
                'city' => 'Milano',
                'state' => 'Italia',
                'latitude' => '45.48122825769107',
                'longitude' => '9.12519998617078',
                'price' => 300.00,
                'image' => '',
                'visibility' => true,
            ],
            [
                'user_id' => 4,
                'name' => 'Résidence au fromage',
                'description' => "Progettato dal celebre designer Robert Riviera, perfetto per coloro che apprezzano l'architettura moderna e minimalista. Gli interni sono caratterizzati da linee pulite e mobili minimalisti, creando un'atmosfera elegante e contemporanea. La zona living è composta da un ampio divano e una cucina completamente attrezzata, mentre la camera da letto dispone di un letto matrimoniale e un armadio a muro. Il bagno è dotato di una grande doccia a pioggia. L'appartamento si trova in una posizione centrale, vicino a numerosi negozi di design e ristoranti di tendenza.",
                'square_meters' => 190,
                'bed_number' => 7,
                'bathroom_number' => 3,
                'room_number' => 5,
                'address' => 'Piazza Castello, 3 20121 Milano MI',
                'city' => 'Milano',
                'state' => 'Italia',
                'latitude' => '45.47295873762749',
                'longitude' => '9.177989838881677',
                'price' => 390.00,
                'image' => '',
                'visibility' => true,
            ]
            
        ];
        foreach ($apartments as $apartment) {
            Apartment::create([
                'user_id' => $apartment['user_id'],
                'name' => $apartment['name'],
                'slug' => Str::slug($apartment['name'], '_'),
                'description' => $apartment['description'],
                'square_meters' => $apartment['square_meters'],
                'bed_number' => $apartment['bed_number'],
                'bathroom_number' => $apartment['bathroom_number'],
                'room_number' => $apartment['room_number'],
                'address' => $apartment['address'],
                'city' => $apartment['city'],
                'state' => $apartment['state'],
                'latitude' => $apartment['latitude'],
                'longitude' => $apartment['longitude'],
                'price' => $apartment['price'],
                'image' => $apartment['image'],
                'visibility' => $apartment['visibility'],
            ]);
        }
    }
}
